---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    field.cattle.io/projectId: c-bd7z2:p-7ms8p
  name: sample-next-app-test2
  
---
apiVersion: v1
kind: Pod
metadata:
  name: rss-site
  namespace: sample-next-app-test2
  annotations:
    "janitor/ttl": "1m"
  labels:
    app: web
spec:
  containers:
    - name: pod1
      image: nginx
      ports:
        - containerPort: 80
    - name: pod2
      image: nickchase/rss-php-nginx:v1
      ports:
        - containerPort: 88
