apiVersion: v1
kind: Pod
metadata:
  name: rss-site
  labels:
    app: web
spec:
  containers:
    - name: pod1
      image: nginx
      ports:
        - containerPort: 80
    - name: pod2
      image: nickchase/rss-php-nginx:v1
      ports:
        - containerPort: 88
